const dogBreeds = [
    'Akita',
    'American Staffordshire Terrier',
    'Australian Shepherd',
    'Beagle',
    'Belgian Malinois',
    'Bernese Mountain Dog',
    'Border Collie',
    'Boston Terrier',
    'Boxer',
    'Bulldog',
    'Bullmastiff',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Dachshund',
    'Doberman Pinscher',
    'English Bulldog',
    'French Bulldog',
    'German Shepherd',
    'Golden Retriever',
    'Great Dane',
    'Havanese',
    'Jack Russell Terrier',
    'Labrador Retriever',
    'Lhasa Apso',
    'Maltese',
    'Miniature Schnauzer',
    'Pomeranian',
    'Poodle',
    'Pug',
    'Rottweiler',
    'Shar Pei',
    'Shih Tzu',
    'Siberian Husky',
    'Staffordshire Bull Terrier',
    'Welsh Corgi',
    'West Highland White Terrier',
    'Yorkshire Terrier',
    'Affenpinscher',
    'Basset Hound',
    'Bichon Frise',
    'Bloodhound',
    'Brittany Spaniel',
    'Chow Chow',
    'Cocker Spaniel',
    'Cane Corso',
    'Dalmatian',
    'English Springer Spaniel',
    'Greyhound',
    'Irish Wolfhound'
   ];
   
module.exports = dogBreeds.sort();