const israelCities = [
  'Jerusalem',
  'Tel Aviv Yafo',
  'Haifa',
  'Ashdod',
  'Rishon Letzion',
  'Petach Tikwa',
  'Beer Sheva',
  'Netanya',
  'Holon',
  'Bnei Brak',
  'Rehovot',
  'Bat Yam',
  'Ramat Gan',
  'Ashkelon',
  'Modiin',
  'Herzeliya',
  'Kefar Sava',
  'Raanana',
  'Hadera',
  'Beit Shemesh',
  'Lod',
  'Nazerat',
  'Modiin Ilit',
  'Ramla',
  'Eilat',
  'Neharia',
  'Kiriat Ata',
  'Givataim',
  'Elad',
  'Kiriat Gat',
  'Aco',
  'Afula',
  'Carmiel',
  'Hod Hasharon',
  'Shefaram',
  'Nof Hagalil',
  'Umm el Fahm',
  'Kiriat Ono',
  'Tiberias',
  'Kiriat Motzkin',
  'Kiriat Yam',
  'Rosh Haain',
  'Nes Ziona',
  'Kiriat Bialik',
  'Ramat Hasharon',
  'Dimona',
  'Yavne',
  'Or Yehuda',
  'Yehud Monosson',
  'Zefat',
  'Gadra',
  'Beer Yaakov',
  'Tamara',
  'Migdal Haemek',
  'Sachnin',
  'Netivot',
  'Mevaseret Zion',
  'Ofakim',
  'Arad',
  'Yokneam Ilit',
  'Kiriat Malachi',
  'Zichron Yaakov',
  'Kadima - Zoran',
  'Gan Yavne',
  'Kiriat Shmone',
  'Kefar Yona',
  'Maalot Tarshia',
  'Nesher',
  'Shoham',
  'Sderot',
  'Tel Sheva',
  'Rahat',
  'Tirat Hacarmel',
  'Ariel',
  'Givat Shmuel',
  'Kriat Tivon',
  'Azur',
  'Beit Shean',
  'Ganei Tikwa'
];

module.exports = israelCities.sort();
